### ISSUE TITLE
Local tests not passing for test_config.py and test_geodesy.py

### ISSUE THREAD

**Issue by lewisblake** [metno/pyaerocom#1091] opened 2024-04-04 13:07 UTC
**Describe the bug**
Local and tests on PPI are not passing. Please see below for details.

 - Pyaerocom version: 0.16.0 main-dev
 - Computing platform: Local & PPI
 - Configuration file (if applicable):
 - Error message (if applicable):

**To Reproduce**
1. pull latest changes from main-dev
2. pytest

```console
==================================================================================================================================== short test summary info ====================================================================================================================================
FAILED tests/test_config.py::test_Config_read_config[metno-None-False-False-0] - AssertionError: assert 30 == 0
FAILED tests/test_config.py::test_Config_read_config[metno-None-True-False-0] - AssertionError: assert 30 == 0
FAILED tests/test_config.py::test_Config_read_config[metno-None-True-True-0] - AssertionError: assert 30 == 0
FAILED tests/test_config.py::test_Config_read_config[metno-/home/lewisb-True-True-2] - AssertionError: assert 30 == 2
FAILED tests/test_geodesy.py::test_etopo_altitude - FileNotFoundError: [Errno 2] No such file or directory: '/home/lewisb/.geonum/ETOPO1_Ice_g_gmt4.grd'

Results (340.16s (0:05:40)):
    1747 passed
       1 xpassed
       5 failed
         - tests/test_config.py:115 test_Config_read_config[metno-None-False-False-0]
         - tests/test_config.py:115 test_Config_read_config[metno-None-True-False-0]
         - tests/test_config.py:115 test_Config_read_config[metno-None-True-True-0]
         - tests/test_config.py:115 test_Config_read_config[metno-/home/lewisb-True-True-2]
         - tests/test_geodesy.py:42 test_etopo_altitude
       3 xfailed
      11 skipped
```
  
**Expected behavior**
Local tests to pass. This is a checklist item for PRs.

**Comment by avaldebe** [comment] 2024-04-04 13:22
this is a duplicate of #1050 and #1054

**Closed as completed by avaldebe** 2024-04-04 13:22 UTC
Labels: bug :bug:, duplicate, testing
