### ISSUE TITLE
Issue with reading routine ReadGaw and associated tests

### ISSUE THREAD

**Issue by jgliss** [metno/pyaerocom#45] opened 2019-10-04 06:46 UTC
After merging #37 into v080DEV tests related to `read_gaw.py` module fail. This needs to be investigated before using this module on an operational basis.

**Comment by hannasv** [comment] 2019-12-10 15:15
There appears to be an issue with units when reading less than all variables available. This dataset consist of six files. Five of these variables are Amsterdam Island and Cape Verde Observatory. DMS is present in both. The last four variables are from Amsterdam Island. Reading in one variable, currently generates 6 stations, where 5 of them have empty attributes in the metadata block...

Not really sure how to solve this, without hard coding which files to read based on the variables requested. Question, should one variable be read into one station data object? And then merged..? @jgliss

**Comment by hannasv** [comment] 2019-12-10 15:17
For examples on the metadata block see https://github.com/metno/pyaerocom-tutorials/blob/master/notebooks/dev/DMS.ipynb

**Comment by paulina-t** [comment] 2019-12-10 18:45
Hi,

You're right. This test should be deleted (or eventually updated). The main changes to the read_gaw.py file since the tests worked are:

1) The routine reads all the files in the directory, whereas it used to only read DMS data at Amsterdam Island and Cape Verde.
 
2) The units were changed to match those of the pyaerocom convention (they've only changed by a factor of 10^6).  This means that the units are no longer the ones in the paper of Sciare et al. (2000). Also, remember that the definition of some new variables was proposed.

I believe that, after finding the paper, the idea was to reproduce the figures in the paper with this dataset and compare them. The figures can be obtained by running the file as a script or by opening the associated notebook. You'll see that the results are similar, but not the same. The small differences are due to differences in the datasets (I sent an email to J. Sciare asking for an updated version but didn't get an answer). If you still want to write the test functions, I recommend to establish a tolerance and compare the mean an deviation. These have already been calculated and are provided in the paper.

Since I have no longer access to the data, I can't test the code. However, let me know if anything is unclear.

**Comment by avaldebe** [comment] 2022-01-03 09:53
`read_gaw.py` has no test and is ignored from the coverage. I suspect this module is no longer used.

https://github.com/metno/pyaerocom/blob/3e8048895bbd403e504a99e38967f43afc441dbf/pyproject.toml#L16-L29

**Closed by avaldebe** 2022-01-03 09:53 UTC
Labels: bug, help wanted
